server:
  port: 9090
  servlet:
    context-path: /shop-manager


spring:
#  数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?..............
    username:
    password:

#    指定连接池和连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1   #初始连接数
      max-active: 20    #最大连接数
      max-idle: 20      #最大空间
      min-idle: 1       #最小空间
      max-wait: 60000   #最长等待时间

  freemarker:
    cache: false
    charset: UTF-8
    content-type: text/html;charset=UTF-8
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/views/

    #    配置模板里是否可以直接取request的属性 request是别名
    request-context-attribute: request
    #配置将request和session中的键值对添加到AbstractTemplateView类的renderMergedOutputModel方法中的model这个map参数中
    expose-request-attributes: true
    expose-spring-macro-helpers: true

    #配置模板里是否可以直接取session
    expose-session-attributes: true
    settings:
      tag_syntax: auto_detect #配置标签语法为自动，页面可以将<>改成[] 为了区别html标签
      tempate_update_delay: 0 #模板更新时间 单位秒
      default-encodeing: UTF-8 #默认编码
      output_encoding: UTF-8 #模板输出编码
      locale: zh_CN #本地化配置
      date_format: yyyy-MM-dd #日期格式化
      time_format: HH:mm:ss #时间格式化
      datetime_format: yyyy-MM-dd HH:mm:ss #日期时间格式化
      number_format: #.##                  #数字格式化
      boolean_format: true,false    #布尔格式化
      template_exception_handler: html_debug #百度

mybatis:
  #配置返回类型
  type-aliases-package: org/example/manager/pojo
  #配置映射文件
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    org.example.manager.mapper: debug